Configurações As screen:

    Rectangle3_3 As rectangle:
        Fill: =RGBA(125, 86, 162, 1)
        Height: =157
        Width: =1366
        ZIndex: =1

    titulo_2 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =3
        Fill: =RGBA(255, 255, 255, 1)
        FontWeight: =FontWeight.Bold
        Height: =80
        Size: =30
        Text: ="ADICIONAR PESSOA"
        Width: =464
        X: =58
        Y: =412
        ZIndex: =2

    Image1_1 As image:
        Height: =157
        Image: =Marca_Suzano_Vertical_Negativo_PB
        Width: =341
        X: =1025
        ZIndex: =3

    Button2_10 As button:
        Fill: =RGBA(125, 86, 162, 1)
        FocusedBorderColor: =ColorFade(Self.Fill, -75%)
        Height: =98
        HoverFill: =ColorFade(RGBA(125, 86, 162, 1), -20%)
        OnSelect: |-
            =If(IsBlank(combo_pessoas.Selected.Email) <> true,
            'Fluxo-AdicionarMembroLinhadePlanos'.Run(combo_pessoas.Selected.Email);
            Notify("ACESSO CONCEDIDO A " & combo_pessoas.Selected.DisplayName,NotificationType.Success,10000),
            Notify("Você precisar selecionar a pessoa",NotificationType.Error,1000)
            );
            Reset(combo_pessoas)
        Size: =16
        Text: ="CONCEDER ACESSO"
        Width: =269
        X: =134
        Y: =651
        ZIndex: =4

    combo_pessoas As combobox:
        DisplayFields: =["DisplayName","Email","Picture"]
        Height: =116
        InputTextPlaceholder: ="Localizar Pessoas"
        Items: =Choices([@'Pessoas - Adicionadas'].Pessoas)
        SearchFields: =["DisplayName"]
        SearchItems: =Choices('Pessoas - Adicionadas'.Pessoas,combo_pessoas.SearchText)
        SelectMultiple: =false
        Template: =ListItemTemplate.Person
        Width: =464
        X: =58
        Y: =510
        ZIndex: =5

    titulo_3 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        FontWeight: =FontWeight.Bold
        Height: =152
        Size: =43
        Text: ="CONFIGURAÇÕES"
        Width: =1366
        Y: =5
        ZIndex: =9

    Icon1_1 As icon.BackArrow:
        Color: =RGBA(255, 255, 255, 1)
        Height: =109
        Icon: =Icon.BackArrow
        OnSelect: =Navigate(Telainicial,ScreenTransition.Fade)
        Width: =141
        X: =28
        Y: =29
        ZIndex: =10

