Configurações As screen:

    Rectangle3_3 As rectangle:
        Fill: =RGBA(125, 86, 162, 1)
        Height: =157
        Width: =1366
        ZIndex: =1

    titulo_2 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        FontWeight: =FontWeight.Bold
        Height: =157
        Size: =43
        Text: ="CONFIGURAÇÕES"
        Width: =1366
        ZIndex: =2

    Image1_1 As image:
        Height: =157
        Image: =Marca_Suzano_Vertical_Negativo_PB
        Width: =341
        X: =1025
        ZIndex: =3

    Icon1_1 As icon.BackArrow:
        Color: =RGBA(255, 255, 255, 1)
        Height: =109
        Icon: =Icon.BackArrow
        OnSelect: =Navigate(Telainicial,ScreenTransition.Fade)
        Width: =141
        X: =28
        Y: =29
        ZIndex: =4

    Button2_10 As button:
        Fill: =RGBA(71, 35, 105, 1)
        FocusedBorderColor: =ColorFade(Self.Fill, -75%)
        Height: =98
        HoverFill: =ColorFade(RGBA(125, 86, 162, 1), -20%)
        OnSelect: ='Fluxo-AdicionarMembroLinhadePlanos'.Run("")
        Size: =16
        Text: ="ADICIONAR PESSOA"
        Width: =269
        X: =82
        Y: =578
        ZIndex: =5

    combo_pessoas As combobox:
        DisplayFields: =["Mail","DisplayName"]
        Height: =84
        Items: |-
            =UsuáriosdoOffice365.SearchUser({top:10,searchTerm:mail_text.Text})
        SearchFields: =["City"]
        SearchItems: |-
            =Search(UsuáriosdoOffice365.SearchUser({top:10,searchTerm:mail_text.Text}),combo_pessoas.SearchText,"City")
        SelectMultiple: =false
        Template: =ListItemTemplate.Person
        Width: =419
        X: =28
        Y: =457
        ZIndex: =6

    Label2 As label:
        Height: =68
        Text: =UsuáriosdoOffice365.UserPhoto(
        Width: =247
        X: =957
        Y: =347
        ZIndex: =8

    mail_text As text:
        Default: =""
        HintText: ="Digite aqui o Email"
        X: =240
        Y: =250
        ZIndex: =9

    Image3 As image:
        Image: =UsuáriosdoOffice365.UserPhoto("mdsantos")
        X: =560
        Y: =384
        ZIndex: =10

